baseurl = "/"
title = "Not an ordinary trend"
author = "Adrian Huerta"
contentdir = "content"
#contentdir = "content/post"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
FootnoteReturnLinkContents = "↩"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Not an ordinary trend"
  disableWebFonts = false
  
[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Research"
    url  = "/research/"
[[menu.main]]
    name = "Publications"
    url  = "https://www.researchgate.net/profile/Adrian_Huerta/research"